export default {
  login: "harsh2102",
  id: 48135196,
  node_id: "MDQ6VXNlcjQ4MTM1MTk2",
  avatar_url: "https://avatars1.githubusercontent.com/u/48135196?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/harsh2102",
  html_url: "https://github.com/harsh2102",
  followers_url: "https://api.github.com/users/harsh2102/followers",
  following_url:
    "https://api.github.com/users/harsh2102/following{/other_user}",
  gists_url: "https://api.github.com/users/harsh2102/gists{/gist_id}",
  starred_url: "https://api.github.com/users/harsh2102/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/harsh2102/subscriptions",
  organizations_url: "https://api.github.com/users/harsh2102/orgs",
  repos_url: "https://api.github.com/users/harsh2102/repos",
  events_url: "https://api.github.com/users/harsh2102/events{/privacy}",
  received_events_url: "https://api.github.com/users/harsh2102/received_events",
  type: "User",
  site_admin: false,
  name: "Harsh Mishra",
  company: null,
  blog: "",
  location: "Greater Noida",
  email: null,
  hireable: true,
  bio: "Web developer | Android Developer | Data Analyst \r\n",
  twitter_username: null,
  public_repos: 23,
  public_gists: 0,
  followers: 8,
  following: 1,
  created_at: "2019-03-01T18:24:30Z",
  updated_at: "2020-07-03T16:55:13Z",
};
